export const SET_FORM_FOCUS = 'SET_FORM_FOCUS';
export const SET_FORM_VALUES = 'SET_FORM_VALUES';

export const FETCH_ENTITY = 'FETCH_ENTITY';
export const SAVE_ENTITY = 'SAVE_ENTITY';
export const REMOVE_ENTITY = 'REMOVE_ENTITY';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const RESET_MESSAGES = 'RESET_MESSAGES';
